### ISSUE TITLE
bug in v 2.7.1

### ISSUE THREAD

**Issue by heshesh2010** [mo-ah-dawood/my_fatoorah#10]
Hi , 

there is missing in excutePaymentRequest

url for test : https://apitest.myfatoorah.com/v2/ExecutePayment

token:  rLtt6JWvbUHDDhsZnfpAhpYk4dxYDQkbcPTyGaKp2TYqQgG7FGZ5Th_WD53Oq8Ebz6A53njUoo1w3pjU1D4vs_ZMqFiz_j0urb_BH9Oq9VZoKFoJEDAbRZepGcQanImyYrry7Kt6MnMdgfG5jn4HngWoRdKduNNyP4kzcp3mRv7x00ahkm9LAK7ZRieg7k1PDAnBIOG3EyVSJ5kK4WLMvYr7sCwHbHcu4A5WwelxYK0GMJy37bNAarSJDFQsJ2ZvJjvMDmfWwDVFEVe_5tOomfVNt6bOg9mexbGjMrnHBnKnZR1vQbBtQieDlQepzTZMuQrSuKn-t5XZM7V6fCW7oP-uXGX-sMOajeX65JOf6XVpk29DP6ro8WTAflCDANC193yof8-f5_EYY-3hXhJj7RBXmizDpneEQDSaSz5sFk0sV5qPcARJ9zGG73vuGFyenjPPmtDtXtpx35A-BVcOSBYVIWe9kndG3nclfefjKEuZ3m4jL9Gg1h2JBvmXSMYiZtp9MR5I6pvbvylU_PP5xJFSjVTIz7IQSjcVGO41npnwIxRXNRxFOdIUHn0tjQ-7LwvEcTXyPsHXcMD8WtgBh-wxR8aKX7WPSsT1O8d8reb2aR7K3rkV3K82K_0OgawImEpwSvp9MNKynEAJQS6ZHe_J_l77652xwPNxMRTMASk1ZsJ

body request : 
{"PaymentMethodId":4,"CustomerName":"هشام ‏النمد","DisplayCurrencyIso":"SAR","MobileCountryCode":"966","CustomerMobile":"591111074","CustomerEmail":"hesham.elnemr@gmail.com","InvoiceValue":1145.0,"Language":"AR"}

response : 

{"IsSuccess":false,"Message":"Invalid data","ValidationErrors":[{"Name":"executePayment.CallBackUrl","Error":"The CallBackUrl field is required."},{"Name":"executePayment.ErrorUrl","Error":"The ErrorUrl field is required."}],"Data":null}

**Comment by mo-ah-dawood** [comment]
can you please set your code

**Comment by mo-ah-dawood** [comment]
I think you don't pass errorUrl

**Comment by mo-ah-dawood** [comment]
```dart
import 'package:my_fatoorah/my_fatoorah.dart';
...
 MyFatoorah(
        onResult:(response){
            print(res.status);
        }
        request: MyfatoorahRequest(
                      currencyIso: Country.SaudiArabia,
                      successUrl: ///<-------- required
                          "Your success call back",
                      errorUrl: ///<-------- required
                          "Your error call back",
                      invoiceAmount: 100,
                      language: ApiLanguage.Arabic,
                      token: "Your token here",
                      afterPaymentBehaviour:AfterPaymentBehaviour.None, //See the describe for this property for more details
                      ),
 );
```

**Comment by heshesh2010** [comment]
Hi , here is my code :


```
 MyFatoorah.startPayment(
      context: context,
      request: MyfatoorahRequest(
        currencyIso: Country.SaudiArabia,
        customerEmail: currentUser.value.data.email,
        customerMobile: currentUser.value.data.mobile.replaceAll("966", ""),
        customerName: currentUser.value.data.name,
        successUrl: "https://test.com",
        errorUrl: "https://test.com",
        url: "https://apitest.myfatoorah.com",
        invoiceAmount: order.total.toDouble(),
        language: ApiLanguage.Arabic,
        mobileCountryCode: "966",
        token:
        'rLtt6JWvbUHDDhsZnfpAhpYk4dxYDQkbcPTyGaKp2TYqQgG7FGZ5Th_WD53Oq8Ebz6A53njUoo1w3pjU1D4vs_ZMqFiz_j0urb_BH9Oq9VZoKFoJEDAbRZepGcQanImyYrry7Kt6MnMdgfG5jn4HngWoRdKduNNyP4kzcp3mRv7x00ahkm9LAK7ZRieg7k1PDAnBIOG3EyVSJ5kK4WLMvYr7sCwHbHcu4A5WwelxYK0GMJy37bNAarSJDFQsJ2ZvJjvMDmfWwDVFEVe_5tOomfVNt6bOg9mexbGjMrnHBnKnZR1vQbBtQieDlQepzTZMuQrSuKn-t5XZM7V6fCW7oP-uXGX-sMOajeX65JOf6XVpk29DP6ro8WTAflCDANC193yof8-f5_EYY-3hXhJj7RBXmizDpneEQDSaSz5sFk0sV5qPcARJ9zGG73vuGFyenjPPmtDtXtpx35A-BVcOSBYVIWe9kndG3nclfefjKEuZ3m4jL9Gg1h2JBvmXSMYiZtp9MR5I6pvbvylU_PP5xJFSjVTIz7IQSjcVGO41npnwIxRXNRxFOdIUHn0tjQ-7LwvEcTXyPsHXcMD8WtgBh-wxR8aKX7WPSsT1O8d8reb2aR7K3rkV3K82K_0OgawImEpwSvp9MNKynEAJQS6ZHe_J_l77652xwPNxMRTMASk1ZsJL',
      ),
    )
```

**Comment by mo-ah-dawood** [comment]
There is no url like that in package code

https://apitest.myfatoorah.com/v2/DirectPayment

DirectPayment is not supported by this package

Can you please tell me the steps

**Comment by heshesh2010** [comment]
it works now , but i see .then((response). not called after payment success 

see https://share.getcloudapp.com/RBuY0zQk

**Comment by mo-ah-dawood** [comment]
you have to move afterPaymentBehaviour outside the request 
and please use the latest version if possible 3.0.2

**Comment by heshesh2010** [comment]
it works now 

thanks 

closed
