### ISSUE TITLE
then((response) not called

### ISSUE THREAD

**Issue by heshesh2010** [mo-ah-dawood/my_fatoorah#12]
Hi , 

I'm using this url from backend when payment success : 

 successUrl:
            "https://tavedl.com/checkStatus?userId=${currentUser.value.id}${payment?.coupon==null? "": "&{coupon_code=${payment.coupon}" }&food_type=${payment.type}",

it works , but i want my app to navigate to new screen so .then((response) not called , it's called when i hit backbutton in my app , 

so how to call .then((response)

**Comment by mo-ah-dawood** [comment]
pass this property
`afterPaymentBehaviour: AfterPaymentBehaviour.AfterCalbacksExecution,`
