### ISSUE TITLE
After Payment Complete  Response was null

### ISSUE THREAD

**Issue by Pedasingu-Vijay-Krishna** [mo-ah-dawood/my_fatoorah#2]
Hi...,

Thank You For your dev. iam using your plugin in flutter ...  After payment complete response was null

**Comment by mo-ah-dawood** [comment]
I'm using myfatoorah sdk so that it may  be its an issue in the sdk itself 
but i think your issue is that your callback url returning nothing or it does not exists
as the sdk redirect to this url after payment complete
so this url has to show html content  may be succcess message

**Comment by Pedasingu-Vijay-Krishna** [comment]
Can U tell me the what response is getting from sdk after payment done

**Comment by Pedasingu-Vijay-Krishna** [comment]
Ios is showing error minimum sdk level to set 10

**Comment by mo-ah-dawood** [comment]
please version 2 and read the new docs
