### ISSUE TITLE
Using callBackUrl and errorUrl with firebase dynamic links

### ISSUE THREAD

**Issue by Samar777** [mo-ah-dawood/my_fatoorah#3]
I am trying to assign a deep links to callBackUrl  and errorUrl but no response after payment was complete, and this error appears : type 'double' is not a subtype of type 'int'

my code:

`void excutePayment(int id,) {
    MyFatoorah.executePayment(ExcutePaymentRequest(
      callBackUrl: linkP,
      errorUrl: linkF,
      invoiceAmount: widget.val2,
      paymentMethod: id,
      language: ApiLanguage.Arabic
    ));
  }

  create1() async {
    await createDynamicLinkPaid(paid: "paid");

  }

  create2() async {
     await createDynamicLinkFailed(failed: "failed");
  }

  Future<Uri> createDynamicLinkPaid({@required String paid}) async {
    final DynamicLinkParameters parameters = DynamicLinkParameters(
      uriPrefix: 'https://universitymarket.page.link',
      link: Uri.parse('https://universitymarket.page.link/status?paid=$paid'),
      androidParameters: AndroidParameters(
        packageName: 'market.universities.app',
        minimumVersion: 1,
      ),
      iosParameters: IosParameters(
        bundleId: 'market.universities.app',
        minimumVersion: '1',
        appStoreId: '',
      ),
    );
    final linkP = await parameters.buildUrl();
    print('paid generated');
    return linkP;
  }

  Future<Uri> createDynamicLinkFailed({@required String failed}) async {
    final DynamicLinkParameters parameters = DynamicLinkParameters(
      uriPrefix: 'https://universitymarket.page.link',
      link: Uri.parse('https://universitymarket.page.link/status?failed=$failed'),
      androidParameters: AndroidParameters(
        packageName: 'market.universities.app',
        minimumVersion: 1,
      ),
      iosParameters: IosParameters(
        bundleId: 'market.universities.app',
        minimumVersion: '1',
        appStoreId: '',
      ),
    );
    final linkF = await parameters.buildUrl();
    print('failed link generated');
    return linkF;
  }`

**Comment by mo-ah-dawood** [comment]
callback url must be valid url with html content as it will be shown in webview
as you are using dynamic link you must pass a link when creating your dynamic link
like this
![image](https://user-images.githubusercontent.com/31937782/75608618-c79cd980-5b09-11ea-900e-ac1f185dad54.png)
then https://example.com will be shown
the best thing you can do is   to use a url that show an error message or success message


hope this helps you
