### ISSUE TITLE
Unhandled Exception: Exception: The payment is not completed

### ISSUE THREAD

**Issue by xNoEndx** [mo-ah-dawood/my_fatoorah#5]
Hi, would like to report this bug, when you exit the payment in in the middle of the transaction (filling the credit card number or other payments method), I get below error.

`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: The payment is not completed
#0      MyFatoorah.startPayment.<anonymous closure> (package:my_fatoorah/my_fatoorah.dart:43:9)
#1      _rootRunUnary (dart:async/zone.dart:1134:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43<…>
`

Update: I have added below workaround to catch this error.

`.catchError((onError) {
      print(onError.toString());
      setState(() {
        paymentStatus = 'Fail';
      });
    }`

**Comment by mo-ah-dawood** [comment]
This not an issue,
This the expected behavior if you not complete the payment as the payment method returns future
then the plugin throw an exception if the payment not success nor fail
so if you need to catch this error, you can do that 
else just leave it as it is no thing will happen the exception will be visible in console but has no effect

**Comment by xNoEndx** [comment]
Thanks for the reply, I need to capture the payment incompletion.

appreciated.
