### ISSUE TITLE
previous version 

### ISSUE THREAD

**Issue by hassan4000** [mo-ah-dawood/my_fatoorah#6]
what is the difference between your library and this library
https://pub.dev/packages/myfatoorah_flutter
it is the same name 
please help me

**Comment by mo-ah-dawood** [comment]
Both do the same thing but different in usage 
my plugin is older than the other 
The other is from my fatoorah team
My plugin use one method to handle the payment 
The other usage is same as native usage
Both uses webview for payment

I created mine before my fatoorah team release their own one so you can use what you prefer its up to you
