### ISSUE TITLE
error in 

### ISSUE THREAD

**Issue by heshesh2010** [mo-ah-dawood/my_fatoorah#9]
Hi,
I'm using "  my_fatoorah: ^2.6.5 "

here is the response from myFatoorah gateway :

{"Message":"An error has occurred.","ExceptionMessage":"Value cannot be null.\r\nParameter name: source","ExceptionType":"System.ArgumentNullException","StackTrace":"   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at MF_Vendors.API.AuthorizeVendorAttribute.GetUserRoles(String countryIsoCode, String userId)\r\n   at MF_Vendors.API.AuthorizeVendorAttribute.OnAuthorization(HttpActionContext actionContext)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}

my code: 

     MyFatoorah.startPayment(
      context: this.scaffoldKey.currentState.context,
      request: MyfatoorahRequest(
        currencyIso: Country.SaudiArabia,
        customerEmail: "fdfdf@dfdf.com",
        customerMobile: "43434",
        customerName: "HESHESH",
        successUrl:
            "https://assets.materialup.com/uploads/473ef52c-8b96-46f7-9771-cac4b112ae28/preview.png",
        errorUrl:
            "https://www.digitalpaymentguru.com/wp-content/uploads/2019/08/Transaction-Failed.png",
        invoiceAmount: payment.amount,
        language: ApiLanguage.Arabic,
        token:null,
    //    afterPaymentBehaviour: AfterPaymentBehaviour.BeforeCalbacksExecution,
      ),
    )

**Comment by mo-ah-dawood** [comment]
Will be fixed soon its just the test token has changed in my fatoorah api 
but if you are using your token it will work
